### ISSUE TITLE
Device list should be queried at menu interaction time.

### ISSUE THREAD

**Issue by BartMassey** [dylagit/audio-limiter#2]
The available devices may change while this app is running. Thus, instead of storing a device list as app context, the GUI should query the current device list when a device menu is pulled down.

**Comment by sigaloid** [comment]
I can't figure out how to call an update of the device list when the menu is opened (the callback is called every time so every frame where the mouse moves, it would update it; not very efficient). But, I made a pull request to add a refresh devices button.
