### ISSUE TITLE
Ring buffer in stream seems unneeded?

### ISSUE THREAD

**Issue by BartMassey** [dylagit/audio-limiter#4]
I don't understand why there's a ring buffer providing latency? The compressor doesn't seem to use it, instead using a decaying average.

**Comment by dylagit** [comment]
Hmm, I thought it was necessary? I'd love to remove it if possible. I based that design off of this `cpal` example: 

https://github.com/RustAudio/cpal/blob/master/examples/feedback.rs#L132

where they used a ringbuffer to forward audio from one device to another.

**Comment by BartMassey** [comment]
Oh, I see what they are doing. That code is not great, but yeah, they want to make sure that jitter doesn't get them in trouble. Sorry, my bad.

**Comment by dylagit** [comment]
No problem! And yeah if you can think of a better way to do it I'm all-ears!
